### ISSUE TITLE
"Fetching latest package list from cdn" takes a long time

### ISSUE THREAD

**Issue by LoveAndHappiness** [dafrancis/Sublime-Text--cdnjs#32]
Hi there,

btw I love this plugin. Please help me clarify. 

Everytime I want to use a script I use "import script" after (shift + ctrl + p). Then I always have to wait up until 10 seconds, for sublime to fetch all packages and I am wondering, if I am using it correctly, since it's purpose should be to save time.

**Comment by jourdanritchey** [comment]
Same issue, but the wait time is even longer for me. cdnjs.com loads about 20x faster.

**Comment by rockethouse** [comment]
+1 here, would love to see a fix for this.

**Comment by dafrancis** [comment]
Duplicate of #36

**Comment by sebcl** [comment]
terribly unbearable long, anything we could do to help?
