### ISSUE TITLE
Usage pattern not included

### ISSUE THREAD

**Issue by sathyaprakash94** [dafrancis/Sublime-Text--cdnjs#39]
how to use the cdnjs pacjkage in sublime text3. I installed the package, but usage history to add the libraries is not included with installation.
Result I don't have idea to how to use, even searched in the 
[PackageControl](https://packagecontrol.io/packages/Libraries%20from%20CDN). 

Pls add the commands how to use the package in github or in Package Control.

**Comment by dafrancis** [comment]
The package you've linked is not this package. There are already usage instructions in the `README.md`.
